---
- name: Playbook to add Cluster to a DC
  hosts: localhost
  tasks:
    - name: Add cluster
      community.vmware.vmware_cluster:
        validate_certs: false
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: '{{ datacenter_name }}'
        cluster_name: "Cluster R940"
        state: present
      register: New_cluster_details

  vars:
    vcenter_ip: "100.98.14.248"
    vcenter_hostname: "he-dhcp-100-98-14-248.helab.in"
    vcenter_password: "Dell$1234"
    vcenter_username: "administrator@vsphere.local"
    datacenter_name: "Himanshu DC"
    ansible_python_interpreter: "/usr/bin/python3"

