---
- name: Playbook to add host to cluster
  hosts: localhost
  tasks:
    - name: Add ESXi host
      community.vmware.vmware_host:
        validate_certs: false
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: '{{ datacenter_name }}'
        cluster_name: "Cluster R940"
        esxi_hostname: "esxi-host-ip"
        esxi_username: "root"
        esxi_password: "my@123"
        state: present


  vars:
    vcenter_ip: "vc-ip"
    vcenter_hostname: "vc-fqd-.in"
    vcenter_password: "My$1234"
    vcenter_username: "administrator@vsphere.local"
    datacenter_name: "Himanshu DC"
    ansible_python_interpreter: "/usr/bin/python3"
