---
- name: DC playbook
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Create Datacenter
      community.vmware.vmware_datacenter:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: '{{ datacenter_name }}'
        state: present
        validate_certs: no
      delegate_to: localhost
  vars:
    vcenter_ip: "vc-ip"
    vcenter_hostname: "vc-fqd-.in"
    vcenter_password: "My$1234"
    vcenter_username: "administrator@vsphere.local"
    datacenter_name: "Himanshu DC"
    ansible_python_interpreter: "/usr/bin/python3"
