---
- name: Power On VM
  connection: local
  gather_facts: false
  hosts: localhost
  name: "VMware power on VM"
  tasks:
    -
      name: ForcePowerOn
      vmware_guest_powerstate:
        hostname: "{{vcenter_ip}}"
        name: "{{vmname}}"
        password: "{{vcenter_password}}"
        state: powered-on
        username: "{{vcenter_user}}"
        validate_certs: false
  vars:
    vcenter_ip: "vc-ip"
    vcenter_hostname: "vc-fqdn.in"
    vcenter_password: "My$1234"
    vcenter_username: "administrator@vsphere.local"
    vmname: "vm-name"
    ansible_python_interpreter: "/usr/bin/python3"
