---
- name: Shutdown VM or force power off if exceeds timeout
  connection: local
  gather_facts: false
  hosts: localhost
  name: "VMware power on VM"
  tasks:
    - name: Shutdown guest
      vmware_guest_powerstate:
        hostname: "{{vcenter_ip}}"
        name: "{{vmname}}"
        password: "{{vcenter_password}}"
        state: shutdown-guest
        username: "{{vcenter_user}}"
        state_change_timeout: 10
        validate_certs: false
      ignore_errors: yes
      register: wait

    - name: Force PowerOFF
      vmware_guest_powerstate:
        hostname: "{{vcenter_ip}}"
        name: "{{vmname}}"
        password: "{{vcenter_password}}"
        username: "{{vcenter_user}}"
        state: powered-off
        validate_certs: false
      register: poweroff
      when: wait.msg is search('Timeout')
  vars:
    vcenter_ip: "vc-ip"
    vcenter_hostname: "vc-fqd-.in"
    vcenter_password: "My$1234"
    vcenter_username: "administrator@vsphere.local"
    datacenter_name: "Himanshu DC"
    ansible_python_interpreter: "/usr/bin/python3"
